#!/bin/sh

echo "Installing bower"
npm install -g bower@1.3.8

echo "Installing webapp npm packages"
(cd ../src/webapp/; npm install; npm prune)

echo "Installing webapp bower packages"
(cd ../src/webapp/; bower install; bower prune)

echo "Done installing packages"