webapp:
  build: webapp
  env_file:
    - db/secrets.env
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - webapp:/webapp
    - log:/var/log

db:
  build: db
  env_file:
    - db/secrets.env
  volumes_from:
    - dbdata

dbdata:
  build: dbdata